<a href="https://colab.research.google.com/github/RixzFahad/Natural-Language-Processing/blob/main/Natural_LP_Exec.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## ***Natural Language Processing***

In [1]:
import nltk

nltk.download('punkt')
nltk.download('punkt_tab')   # <-- required in your case

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [2]:
text = """Hey guys,

My name is Fahad Khan. I’m from Uttar Pradesh, and currently in Hyderabad, I’m pursuing a Data Science course with GenAI.

My institute is Medha Edu Tech. Before joining, I explored several coaching centres in Ameerpet, but in the end, I chose this institute.

The main reason was their teaching approach. They first offer a 3-day demo session completely free, so you can experience their teaching style and then decide.

For me, the experience was excellent. They cover everything from the basics to an advanced level — including Python, SQL, and other essential tools required in Data Science.

They also focus on communication skills and English speaking, which play a very important role during interviews.

Our tutor is very kind and supportive. He explains every topic step by step in a simple way and ensures that all our doubts are cleared.

If anyone is interested in joining, feel free to contact me for more details. For enquiries, you can also connect through this page.
"""
sentence = nltk.sent_tokenize(text)
# print(sentence)
for s in sentence:
  print(s)
  print()

Hey guys,

My name is Fahad Khan.

I’m from Uttar Pradesh, and currently in Hyderabad, I’m pursuing a Data Science course with GenAI.

My institute is Medha Edu Tech.

Before joining, I explored several coaching centres in Ameerpet, but in the end, I chose this institute.

The main reason was their teaching approach.

They first offer a 3-day demo session completely free, so you can experience their teaching style and then decide.

For me, the experience was excellent.

They cover everything from the basics to an advanced level — including Python, SQL, and other essential tools required in Data Science.

They also focus on communication skills and English speaking, which play a very important role during interviews.

Our tutor is very kind and supportive.

He explains every topic step by step in a simple way and ensures that all our doubts are cleared.

If anyone is interested in joining, feel free to contact me for more details.

For enquiries, you can also connect through this page.

In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import nltk

In [4]:
import nltk

nltk.download('punkt')      # for tokenization
nltk.download('wordnet')    # lexical database (not "rule book", used for lemmatization)
nltk.download('stopwords')  # common stopwords

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

***Word Tokenization***

In [5]:
from nltk.corpus.reader import wordlist
for w in sentence:
  wordlist = nltk.word_tokenize(w)
  print(wordlist)
  print()

['Hey', 'guys', ',', 'My', 'name', 'is', 'Fahad', 'Khan', '.']

['I', '’', 'm', 'from', 'Uttar', 'Pradesh', ',', 'and', 'currently', 'in', 'Hyderabad', ',', 'I', '’', 'm', 'pursuing', 'a', 'Data', 'Science', 'course', 'with', 'GenAI', '.']

['My', 'institute', 'is', 'Medha', 'Edu', 'Tech', '.']

['Before', 'joining', ',', 'I', 'explored', 'several', 'coaching', 'centres', 'in', 'Ameerpet', ',', 'but', 'in', 'the', 'end', ',', 'I', 'chose', 'this', 'institute', '.']

['The', 'main', 'reason', 'was', 'their', 'teaching', 'approach', '.']

['They', 'first', 'offer', 'a', '3-day', 'demo', 'session', 'completely', 'free', ',', 'so', 'you', 'can', 'experience', 'their', 'teaching', 'style', 'and', 'then', 'decide', '.']

['For', 'me', ',', 'the', 'experience', 'was', 'excellent', '.']

['They', 'cover', 'everything', 'from', 'the', 'basics', 'to', 'an', 'advanced', 'level', '—', 'including', 'Python', ',', 'SQL', ',', 'and', 'other', 'essential', 'tools', 'required', 'in', 'Data', 'Science', '.']

['They', 'also', 'focus', 'on', 'communication', 'skills', 'and', 'English', 'speaking', ',', 'which', 'play', 'a', 'very', 'important', 'role', 'during', 'interviews', '.']

['Our', 'tutor', 'is', 'very', 'kind', 'and', 'supportive', '.']

['He', 'explains', 'every', 'topic', 'step', 'by', 'step', 'in', 'a', 'simple', 'way', 'and', 'ensures', 'that', 'all', 'our', 'doubts', 'are', 'cleared', '.']

['If', 'anyone', 'is', 'interested', 'in', 'joining', ',', 'feel', 'free', 'to', 'contact', 'me', 'for', 'more', 'details', '.']

['For', 'enquiries', ',', 'you', 'can', 'also', 'connect', 'through', 'this', 'page', '.']

***Remove The StopWords***

*   Stemming :- Crude Approch
*   Lemmatization :- Rule Based Approach

In [6]:
from nltk.corpus import stopwords
import string

In [7]:
#Stemming Is A Crude Approach Where It Not Works Always Becasue It Removes Last Letter Like Ing, Ed, Er Etc
#Mostly Stemming Won't Works With Simple Past Text Data.
#To Avoid This Problem We Use The Lemmatization.
#Lemmatization Is A Rule Based Approach To Get The Root Words.

In [8]:
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer
stop_words = set(stopwords.words('english'))
print(stop_words)
#Initializing The Stemming And Lemmatizer
lemmatizer = WordNetLemmatizer()
stemmer = PorterStemmer()

for w in sentence:
    words = nltk.word_tokenize(w)

    # remove punctuations
    words = [word for word in words if word not in string.punctuation]

    # remove stop words
    words = [word for word in words if word.lower() not in stop_words]

    # get root words
    lemmatized_words = [lemmatizer.lemmatize(word) for word in words]
    stemming_words = [stemmer.stem(word) for word in words]

    print("Original word:", w)
    print("Lemmatized words:", lemmatized_words)
    print("Stemming words:", stemming_words)
    print()

{'theirs', 'a', 'there', "shouldn't", "mightn't", 'to', 'when', "they'll", "she'd", "i'll", 't', 'will', 'my', 'needn', 'we', "we've", 'hers', 'own', "don't", 'over', 's', "he's", "didn't", 'myself', 'under', 'same', 'than', 'him', 'wasn', 'been', "weren't", 'herself', 'its', "he'd", 'or', "shan't", "it'd", 'further', 'that', 'all', 'did', 'at', 'his', 'd', 'yours', "isn't", "doesn't", "you'll", 'shouldn', 've', 'most', 'it', 'isn', "you're", "he'll", 'between', 'should', 'mustn', 'ours', 'have', "i'd", 'then', "wouldn't", "they're", 'them', "we'd", 'an', 'during', "they'd", 'has', 'after', 'does', 'down', 'aren', 'now', 'where', "you'd", 'again', "won't", 'was', 'ma', 'had', 'don', "couldn't", "you've", 'such', 'they', 'as', 'being', 'having', 'from', 'nor', 'hadn', 'be', 'she', "hasn't", 'in', 'more', "we'll", 'just', "we're", 'weren', 'other', 'is', "should've", 'o', 'how', 'by', 're', "it's", 'were', 'can', 'but', "she'll", 'y', 'haven', 'doing', 'once', 'these', 'this', 'their', 'her', 'itself', 'which', 'here', "they've", "hadn't", 'about', "haven't", 'up', 'any', 'our', 'before', 'with', 'off', "needn't", 'through', 'yourselves', 'only', 'mightn', 'against', 'of', 'not', 'i', 'themselves', 'ain', 'am', 'are', 'into', "it'll", 'll', 'who', 'if', 'whom', 'won', 'because', 'and', 'doesn', 'himself', 'too', 'both', 'yourself', 'hasn', 'why', "i've", 'out', 'wouldn', "that'll", 'm', 'the', "i'm", 'for', 'each', 'few', 'me', 'ourselves', 'while', 'on', "wasn't", "mustn't", 'shan', 'no', "aren't", 'didn', 'below', 'couldn', 'do', 'above', "she's", 'very', 'you', 'he', 'those', 'some', 'what', 'so', 'your', 'until'}
Original word: Hey guys,

My name is Fahad Khan.
Lemmatized words: ['Hey', 'guy', 'name', 'Fahad', 'Khan']
Stemming words: ['hey', 'guy', 'name', 'fahad', 'khan']

Original word: I’m from Uttar Pradesh, and currently in Hyderabad, I’m pursuing a Data Science course with GenAI.
Lemmatized words: ['’', 'Uttar', 'Pradesh', 'currently', 'Hyderabad', '’', 'pursuing', 'Data', 'Science', 'course', 'GenAI']
Stemming words: ['’', 'uttar', 'pradesh', 'current', 'hyderabad', '’', 'pursu', 'data', 'scienc', 'cours', 'genai']

Original word: My institute is Medha Edu Tech.
Lemmatized words: ['institute', 'Medha', 'Edu', 'Tech']
Stemming words: ['institut', 'medha', 'edu', 'tech']

Original word: Before joining, I explored several coaching centres in Ameerpet, but in the end, I chose this institute.
Lemmatized words: ['joining', 'explored', 'several', 'coaching', 'centre', 'Ameerpet', 'end', 'chose', 'institute']
Stemming words: ['join', 'explor', 'sever', 'coach', 'centr', 'ameerpet', 'end', 'chose', 'institut']

Original word: The main reason was their teaching approach.
Lemmatized words: ['main', 'reason', 'teaching', 'approach']
Stemming words: ['main', 'reason', 'teach', 'approach']

Original word: They first offer a 3-day demo session completely free, so you can experience their teaching style and then decide.
Lemmatized words: ['first', 'offer', '3-day', 'demo', 'session', 'completely', 'free', 'experience', 'teaching', 'style', 'decide']
Stemming words: ['first', 'offer', '3-day', 'demo', 'session', 'complet', 'free', 'experi', 'teach', 'style', 'decid']

Original word: For me, the experience was excellent.
Lemmatized words: ['experience', 'excellent']
Stemming words: ['experi', 'excel']

Original word: They cover everything from the basics to an advanced level — including Python, SQL, and other essential tools required in Data Science.
Lemmatized words: ['cover', 'everything', 'basic', 'advanced', 'level', '—', 'including', 'Python', 'SQL', 'essential', 'tool', 'required', 'Data', 'Science']
Stemming words: ['cover', 'everyth', 'basic', 'advanc', 'level', '—', 'includ', 'python', 'sql', 'essenti', 'tool', 'requir', 'data', 'scienc']

Original word: They also focus on communication skills and English speaking, which play a very important role during interviews.
Lemmatized words: ['also', 'focus', 'communication', 'skill', 'English', 'speaking', 'play', 'important', 'role', 'interview']
Stemming words: ['also', 'focu', 'commun', 'skill', 'english', 'speak', 'play', 'import', 'role', 'interview']

Original word: Our tutor is very kind and supportive.
Lemmatized words: ['tutor', 'kind', 'supportive']
Stemming words: ['tutor', 'kind', 'support']

Original word: He explains every topic step by step in a simple way and ensures that all our doubts are cleared.
Lemmatized words: ['explains', 'every', 'topic', 'step', 'step', 'simple', 'way', 'ensures', 'doubt', 'cleared']
Stemming words: ['explain', 'everi', 'topic', 'step', 'step', 'simpl', 'way', 'ensur', 'doubt', 'clear']

Original word: If anyone is interested in joining, feel free to contact me for more details.
Lemmatized words: ['anyone', 'interested', 'joining', 'feel', 'free', 'contact', 'detail']
Stemming words: ['anyon', 'interest', 'join', 'feel', 'free', 'contact', 'detail']

Original word: For enquiries, you can also connect through this page.
Lemmatized words: ['enquiry', 'also', 'connect', 'page']
Stemming words: ['enquiri', 'also', 'connect', 'page']

In [9]:
document = ['Good Movie good Screenplay', 'good movie','bad movie sleep']
# import libraries To Convert text data into numeric forms
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
import pandas as pd

***Step - One*** **Design The Vocabulary**

In [11]:
count_vectorizer = CountVectorizer(binary=False)

***Step - Two*** **Create A bag Of Words Model**

In [12]:
bag_of_words = count_vectorizer.fit_transform(document)

***Step - Three*** **Show The Bag Of Words As A Pandas DF**

In [13]:
feature_name = count_vectorizer.get_feature_names_out()
pd.DataFrame(bag_of_words.toarray(), columns=feature_name)

   bad  good  movie  screenplay  sleep
0    0     2      1           1      0
1    0     1      1           0      0
2    1     0      1           0      1

***N-Gram Approach*** - **Bi-Gram Approach**

In [15]:
document  = ['good movie good screenplay','good movie','bad movie sleep']
# import library to covert text dat into numerical forms
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

# step 1:- Design the vocabulary
#ngram_range = (2,2) means only bigram
count_vectorizer = CountVectorizer(ngram_range=(2,2))
# step 2:- create a bag of wrods model
bag_of_words = count_vectorizer.fit_transform(document)
# step 3 :- show the bag of words as a pandas dataframe
feature_name = count_vectorizer.get_feature_names_out()
pd.DataFrame(bag_of_words.toarray(),columns=feature_name)

   bad movie  good movie  good screenplay  movie good  movie sleep
0          0           1                1           1            0
1          0           1                0           0            0
2          1           0                0           0            1

***TF-IDF***

In [18]:
document  = ['good movie good screenplay','good movie','bad movie sleep']
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd
tfidf_vectorizer = TfidfVectorizer()
values = tfidf_vectorizer.fit_transform(document)
feature_names = tfidf_vectorizer.get_feature_names_out()
pd.DataFrame(values.toarray(),columns=feature_names)


#Inverse Document Frequency- Term Frequency

        bad      good     movie  screenplay     sleep
0  0.000000  0.794803  0.308618    0.522535  0.000000
1  0.000000  0.789807  0.613356    0.000000  0.000000
2  0.652491  0.000000  0.385372    0.000000  0.652491